services:
    SCode\AmqpRpcTransportBundle\Transport\RpcAmqpTransportFactory:
        arguments: ['@SCode\AmqpRpcTransportBundle\Transport\RpcAmqpTransportFactory.inner']
        decorates: 'messenger.transport.amqp.factory'

    rpc_middleware:
        class: SCode\AmqpRpcTransportBundle\Middleware\RpcMiddleware